# Generated by Django 5.0.6 on 2024-06-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', models.CharField(max_length=100, verbose_name='Prueba')),
                ('resultado', models.CharField(max_length=100, verbose_name='Resultado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Prueba')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='diagnosticos.diagnostico', verbose_name='Diagnóstico')),
            ],
        ),
    ]
