# Generated by Django 5.0.6 on 2024-06-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
